### ISSUE TITLE
提几点建议

### ISSUE THREAD

**Issue by z-ZYS-s** [vusion/md-vue-loader#1]
我调研了一下这帮loaders

```
- vue-markdown-loader
- vue-md-loader
- markdown-to-vue-loader
- v-markdown-loader
- vue-markdown-es6-loader
- vue-markdownit-loader
- md2vue-loader
- markdown-vue-loader
```

其他的loader都做的不咋样，[vue-md-loader](https://github.com/wxsms/vue-md-loader)和我们的有点像，而且它实现的功能也比较完善，我觉得两个可以合并一下。要么完善我们loader的功能，要么给`vue-md-loader`提个PR。

- [x] 两者都不引入vue-loader，比`vue-markdown-loader`好
- [x] `vue-md-loader`的API设计比`vue-markdown-loader`要好一些，就是把markdown单独放在一个对象里
- [x] `vue-markdown-html-loader`需要一个`CacheDir`，我觉得这个没有必要让用户设置，直接找个`.cache`放就行。另外可不可以放在内存里处理，不要走文件的方式
- [ ] `vue-md-loader`不能根据`vue`、`html`来限制转换
- [ ] `vue-md-loader`只能根据一个注释来激活代码
- [ ] `vue-md-loader`加样式会报错
- [x] `vue-markdown-html-loader`对报错不友好

**Comment by zhangsanshi** [comment]
现在报错形式如：
```
ERROR in ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-155c9c1a","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0&bustCa
che!./test/src/test2_md-2-560f98.vue
(Emitted value instead of an instance of Error)
  Error compiling template:

  <p>
      test2 vue. {{a2}}
      <button @click="click">click me</button>
      <button @click={this.click}>click me</button>
  </p>

  - invalid expression: Unexpected token . in

    {this.click}

  Raw expression: @click="{this.click}"
```
可以通过报错信息知道具体报错的文件，形式如: `{filePath}-{vue_index}-{hash}`, 
`filePath` 是相对于运行目录的路径， `vue_index` 是当前 `md` 文件的第几个 `vue` 组件，`hash` 是这个组件内容的 `md5`值的前6位。
举例: `/test/src/test2_md-2-560f98.vue` ，则报错文件路径是 `/test/src/test2.md`,具体报错的 `vue` 组件是文档第 `2` 个。报错信息是
```
(Emitted value instead of an instance of Error)
  Error compiling template:

  <p>
      test2 vue. {{a2}}
      <button @click="click">click me</button>
      <button @click={this.click}>click me</button>
  </p>

  - invalid expression: Unexpected token . in

    {this.click}

  Raw expression: @click="{this.click}"
```

**Comment by z-ZYS-s** [comment]
@click={this.click}这个是个什么。。这不是Regular的写法吗

**Comment by zhangsanshi** [comment]
只是为了演示报错的信息
